from user import User
from credential import Credential


def create_user(fullname,email,mobilenumber):

    new_user = User(fullname,email,mobilenumber)
    return new_user


def create_credential(username, psword, email):

    new_credential = Credential(username,psword,email)
    return new_credential    


def save_user(user):

    user.save_user_details()


def save_cred(credential):

    credential.save_credential()


def del_user(user):
    """
    Function to delete a user
    """
    user.delete_user()


def del_cred(credential):
    """
    Function to delete all users credentials
    """
    credential.delete_credential()


def display_user():
    """
    Function that returns saved users
    """
    return User.display_users()


def display_cred():
    """
    function that returns saved user credentials
    """
    return Credential.display_credential()


def main():

    print("Welcome. Choose an option from the list below")

    while True:
        print("\n sh - sign in to a new user account\n ac- create a new account with autogenerated password\n da - display all user accounts \n ex -exit the contact list \n")            

        short_code = input().lower()

        if short_code == 'sh':
            print("New user")
            print("-"*10)
            print("Please tell us which type of account you'd like to create")
            account = input()
            print(f"We will let you into your {account} in a few")

            print("Full name....")
            full_name = input()

            print("email...")
            email = input()

            print("mobile number...")
            mobile_number = input()

            print("input username...")
            user_name = input()

            print("enter password..")
            psword = input()

            save_user(create_user(full_name,email,mobile_number))   
            save_cred(create_credential(user_name,psword,email))
            print('\n')
            print(f"A new{account} has been created by {full_name}")
            print(f" The username is {user_name} and password {psword} ")
            print('\n')

        elif short_code == 'ac':
            print("New user")
            print("-" * 10)
            print("Which type of account would you like to create?")
            account = input()
            print(f"You will have your {account} account created soon")

            print("Name")
            full_name = input()

            print("email...")
            email = input()

            print("phone number..")
            mobile_number = input()

            print("Username..")
            user_name = input()

            p = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$"
            psword = "".join(random.sample(p, 8))

            save_user(create_user(full_name,email,mobile_number))
            save_cred(create_credential(user_name,psword,email))
            print('\n')
            print(f"A new {account} will be created by {full_name}")
            print(f"Username{user_name} password {psword} ")
            print('\n')

        elif short_code == 'da':

            if display_user():
                print("Here are your accounts")
                print('\n')

                for user in display_user():
                    print(f"{user.full_name} has an account for {account}")

                print('\n')
            else:
                print('\n')
                print("You do not have an existing account")
                print('\n')

        elif short_code == 'ex':
            print(":/ThankYou and Goodbye")
            break
        else:
            print(":(No command allowed")


if __name__ == '__main__':
    main()
